import { Component } from '@angular/core';
import { Router } from '@angular/router';
import { TeamStatistic } from 'src/app/shared/utils/interfaces/team.inteerface';

@Component({
  selector: 'app-team-statistics',
  templateUrl: './team-statistics.component.html',
  styleUrls: ['./team-statistics.component.scss']
})
export class TeamStatisticsComponent {
  public categoryList: any;

  teamStatistics: TeamStatistic = 
    {
      teamIcon: '../../../../assets/img/teams/Cagua.jpeg',
      teamName: 'Cagua',
      teamCategory: 'B',
      points: 25,
      jg: 2,
      jp: 4,
      je: 8,
      players: [
      {
        fullName: 'Jesus Sanchez',
        photo: '../../../assets/img/player.jpeg',
        VB: '9',
        AI: '9',
        HC: '4',
        H1: '3',
        H2: '1',
        H3: '0',
        HR: '0',
        JJ: '2',
        average: '444',
      },
      {
        fullName: 'Vladimir Sanchez',
        photo: '../../../assets/img/player.jpeg',
        VB: '9',
        AI: '9',
        HC: '4',
        H1: '3',
        H2: '1',
        H3: '0',
        HR: '0',
        JJ: '2',
        average: '444',
      },
      {
        fullName: 'Carlos Marques',
        photo: '../../../assets/img/player.jpeg',
        VB: '9',
        AI: '9',
        HC: '4',
        H1: '3',
        H2: '1',
        H3: '0',
        HR: '0',
        JJ: '2',
        average: '444',
      },
      {
        fullName: 'Rigoberto Roso',
        photo: '../../../assets/img/player.jpeg',
        VB: '9',
        AI: '9',
        HC: '4',
        H1: '3',
        H2: '1',
        H3: '0',
        HR: '0',
        JJ: '2',
        average: '444',
      },
      {
        fullName: 'Wilmer Cervantes',
        photo: '../../../assets/img/player.jpeg',
        VB: '9',
        AI: '9',
        HC: '4',
        H1: '3',
        H2: '1',
        H3: '0',
        HR: '0',
        JJ: '2',
        average: '444',
      },
      {
        fullName: 'Jose Coa',
        photo: '../../../assets/img/player.jpeg',
        VB: '9',
        AI: '9',
        HC: '4',
        H1: '3',
        H2: '1',
        H3: '0',
        HR: '0',
        JJ: '2',
        average: '444',
      },
      {
        fullName: 'Orlando Delgado',
        photo: '../../../assets/img/player.jpeg',
        VB: '9',
        AI: '9',
        HC: '4',
        H1: '3',
        H2: '1',
        H3: '0',
        HR: '0',
        JJ: '2',
        average: '444',
      },
      {
        fullName: 'Leandro Perez',
        photo: '../../../assets/img/player.jpeg',
        VB: '9',
        AI: '9',
        HC: '4',
        H1: '3',
        H2: '1',
        H3: '0',
        HR: '0',
        JJ: '2',
        average: '444',
      },
      {
        fullName: 'Luis Peña',
        photo: '../../../assets/img/player.jpeg',
        VB: '9',
        AI: '9',
        HC: '4',
        H1: '3',
        H2: '1',
        H3: '0',
        HR: '0',
        JJ: '2',
        average: '444',
      },
      {
        fullName: 'Jose Alvarado',
        photo: '../../../assets/img/player.jpeg',
        VB: '9',
        AI: '9',
        HC: '4',
        H1: '3',
        H2: '1',
        H3: '0',
        HR: '0',
        JJ: '2',
        average: '444',
      },
      {
        fullName: 'Wilmer Gordillo',
        photo: '../../../assets/img/player.jpeg',
        VB: '9',
        AI: '9',
        HC: '4',
        H1: '3',
        H2: '1',
        H3: '0',
        HR: '0',
        JJ: '2',
        average: '444',
      },
      {
        fullName: 'Luis Piñero',
        photo: '../../../assets/img/player.jpeg',
        VB: '9',
        AI: '9',
        HC: '4',
        H1: '3',
        H2: '1',
        H3: '0',
        HR: '0',
        JJ: '2',
        average: '444',
      },
      {
        fullName: 'Erwin Montilla',
        photo: '../../../assets/img/player.jpeg',
        VB: '9',
        AI: '9',
        HC: '4',
        H1: '3',
        H2: '1',
        H3: '0',
        HR: '0',
        JJ: '2',
        average: '444',
      },
      {
        fullName: 'Kevin Gonzales',
        photo: '../../../assets/img/player.jpeg',
        VB: '9',
        AI: '9',
        HC: '4',
        H1: '3',
        H2: '1',
        H3: '0',
        HR: '0',
        JJ: '2',
        average: '444',
      },
      {
        fullName: 'Karin Nieto',
        photo: '../../../assets/img/player.jpeg',
        VB: '9',
        AI: '9',
        HC: '4',
        H1: '3',
        H2: '1',
        H3: '0',
        HR: '0',
        JJ: '2',
        average: '444',
      },
      {
        fullName: 'Karin Nieto',
        photo: '../../../assets/img/player.jpeg',
        VB: '9',
        AI: '9',
        HC: '4',
        H1: '3',
        H2: '1',
        H3: '0',
        HR: '0',
        JJ: '2',
        average: '444',
      },
      {
        fullName: 'Jhony Gonzalez',
        photo: '../../../assets/img/player.jpeg',
        VB: '9',
        AI: '9',
        HC: '4',
        H1: '3',
        H2: '1',
        H3: '0',
        HR: '0',
        JJ: '2',
        average: '444',
      },
      {
        fullName: 'Hector Perdomo',
        photo: '../../../assets/img/player.jpeg',
        VB: '9',
        AI: '9',
        HC: '4',
        H1: '3',
        H2: '1',
        H3: '0',
        HR: '0',
        JJ: '2',
        average: '444', 
      },
      {
        fullName: 'Endric Gonzalez',
        photo: '../../../assets/img/player.jpeg',
        VB: '9',
        AI: '9',
        HC: '4',
        H1: '3',
        H2: '1',
        H3: '0',
        HR: '0',
        JJ: '2',
        average: '444',
      },
      {
        fullName: 'Jose Ramirez',
        photo: '../../../assets/img/player.jpeg',
        VB: '9',
        AI: '9',
        HC: '4',
        H1: '3',
        H2: '1',
        H3: '0',
        HR: '0',
        JJ: '2',
        average: '444',
      
    }
  ]
}

  constructor(private router: Router) {
    this.categoryList = this.teamStatistics;
  }

  ngOnInit(): void {
    this.categoryList = this.teamStatistics;
    console.log(this.categoryList)
  }

  goToStatistics(){
    this.router.navigateByUrl('/estadisticas');
  }
}

